name: Draft Release
on:
  push:
    branches:
      - main
      - master
      - "feature/dt-7263-ci"
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2
        id: go

      - name: Checkout
        uses: actions/checkout@v4
      - name: Download dependencies
        run: go mod download
      - name: Release
        uses: goreleaser/goreleaser-action@7ec5c2b0c6cdda6e8bbb49444bc797dd33d74dd8
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --snapshot --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
